version: '3.7'

services:  
  web:
    build:
      context: ./x-way
    command: sh -c "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/x-way/web/static
      - media_volume:/home/x-way/web/media
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env.prod    
    depends_on:      
      - db    
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=rabbitmq
        - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    restart: on-failure
    
  celery:
    restart: always
    build:
      context: ./x-way
    command: celery -A core worker -l info -B
    env_file:
      - ./.env.prod
    environment:
      - CELERY_BROKER=amqp://rabbitmq:rabbitmq@rabbit:5672//
    links:
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
      - web    
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - "5432:5432"    
    restart: on-failure
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/x-way/web/static
      - media_volume:/home/x-way/web/media
    ports:
      - "1337:80"
    depends_on:
      - web    
    
volumes:
  postgres_data:
  static_volume:
  media_volume:
